services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8443:443"
      # - "8000:80"
      # - "9090:8080"
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    env_file:
      - .env
    environment:
      - VITE_PORT=4173
    depends_on:
      front:
        condition: service_healthy
      back:
        condition: service_healthy
    restart: "no"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--no-check-certificate", "https://localhost:443"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  back:
    build: ./backend
    container_name: api
    volumes:
      - ./certs:/usr/certs
      - ./backend/app/data:/usr/app/data
      - ./backend/app/public/avatars/custom:/usr/app/dist/public/avatars/custom
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    expose:
      - "3001"
    restart: "no"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  front:
    build: ./frontend
    container_name: front
    volumes:
      - ./certs:/usr/certs
    env_file:
      - .env
    environment:
      - VITE_HOSTNAME=${HOSTNAME:-localhost}
    expose:
      - "4173"
    depends_on:
      back:
        condition: service_healthy
    restart: "no"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
