services:
  back:
    build: ./backend
    container_name: api
    volumes:
      - ../AI:/usr/AI
      - ./backend/app:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    restart: unless-stopped
  front:
    build: ./frontend
    container_name: front
    volumes:
      - ./frontend/app:/usr/app
      - /usr/app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - back
    restart: unless-stopped