export { default as Home } from './Home';
export { default as Registration } from './Registration';
export { default as Connection } from './Connection';
export { default as Dashboard } from './Dashboard';
export { default as NotFoundPage } from './NotFoundPage';
export { default as Game } from './Game';
export { default as auth } from './auth';
export { default as Confirmation } from './Confirmation';
export { default as Reglages } from './Reglages';
